In [1]:
import pandas as pd

In [4]:
# 泰坦尼克号乘客相关信息
data = pd.read_csv("http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic.txt")

In [3]:
data

,row.names,pclass,survived,name,age,embarked,home.dest,room,ticket,boat,sex
0,1,1st,1,"Allen, Miss Elisabeth Walton",29.0000,Southampton,"St Louis, MO",B-5,24160 L221,2,female
1,2,1st,0,"Allison, Miss Helen Loraine",2.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,NaN,female
2,3,1st,0,"Allison, Mr Hudson Joshua Creighton",30.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,(135),male
3,4,1st,0,"Allison, Mrs Hudson J.C. (Bessie Waldo Daniels)",25.0000,Southampton,"Montreal, PQ / Chesterville, ON",C26,NaN,NaN,female
4,5,1st,1,"Allison, Master Hudson Trevor",0.9167,Southampton,"Montreal, PQ / Chesterville, ON",C22,NaN,11,male
5,6,1st,1,"Anderson, Mr Harry",47.0000,Southampton,"New York, NY",E-12,NaN,3,male
6,7,1st,1,"Andrews, Miss Kornelia Theodosia",63.0000,Southampton,"Hudson, NY",D-7,13502 L77,10,female
7,8,1st,0,"Andrews, Mr Thomas, jr",39.0000,Southampton,"Belfast, NI",A-36,NaN,NaN,male
8,9,1st,1,"Appleton, Mrs Edward Dale (Charlotte Lamson)",58.0000,Southampton,"Bayside, Queens, NY",C-101,NaN,2,female
9,10,1st,0,"Artagaveytia, Mr Ramon",71.0000,Cherbourg,"Montevideo, Uruguay",NaN,NaN,(22),male
10,11,1st,0,"Astor, Colonel John Jacob",47.0000,Cherbourg,"New York, NY",NaN,17754 L224 10s 6d,(124),male
11,12,1st,1,"Astor, Mrs John Jacob (Madeleine Talmadge Force)",19.0000,Cherbourg,"New York, NY",NaN,17754 L224 10s 6d,4,female
12,13,1st,1,"Aubert, Mrs Leontine Pauline",NaN,Cherbourg,"Paris, France",B-35,17477 L69 6s,9,female
13,14,1st,1,"Barkworth, Mr Algernon H.",NaN,Southampton,"Hessle, Yorks",A-23,NaN,B,male
14,15,1st,0,"Baumann, Mr John D.",NaN,Southampton,"New York, NY",NaN,NaN,NaN,male
15,16,1st,1,"Baxter, Mrs James (Helene DeLaudeniere Chaput)",50.0000,Cherbourg,"Montreal, PQ",B-58/60,NaN,6,female
16,17,1st,0,"Baxter, Mr Quigg Edmond",24.0000,Cherbourg,"Montreal, PQ",B-58/60,NaN,NaN,male
17,18,1st,0,"Beattie, Mr Thomson",36.0000,Cherbourg,"Winnipeg, MN",C-6,NaN,NaN,male
18,19,1st,1,"Beckwith, Mr Richard Leonard",37.0000,Southampton,"New York, NY",D-35,NaN,5,male
19,20,1st,1,"Beckwith, Mrs Richard Leonard (Sallie Monypeny)",47.0000,Southampton,"New York, NY",D-35,NaN,5,female
20,21,1st,1,"Behr, Mr Karl Howell",26.0000,Cherbourg,"New York, NY",C-148,NaN,5,male
21,22,1st,0,"Birnbaum, Mr Jakob",25.0000,Cherbourg,"San Francisco, CA",NaN,NaN,(148),male
22,23,1st,1,"Bishop, Mr Dickinson H.",25.0000,Cherbourg,"Dowagiac, MI",B-49,NaN,7,male
23,24,1st,1,"Bishop, Mrs Dickinson H. (Helen Walton)",19.0000,Cherbourg,"Dowagiac, MI",B-49,NaN,7,female
24,25,1st,1,"Bjornstrm-Steffansson, Mr Mauritz Hakan",28.0000,Southampton,"Stockholm, Sweden / Washington, DC",NaN,,D,male
25,26,1st,0,"Blackwell, Mr Stephen Weart",45.0000,Southampton,"Trenton, NJ",NaN,NaN,(241),male
26,27,1st,1,"Blank, Mr Henry",39.0000,Cherbourg,"Glen Ridge, NJ",A-31,NaN,7,male
27,28,1st,1,"Bonnell, Miss Caroline",30.0000,Southampton,"Youngstown, OH",C-7,NaN,8,female
28,29,1st,1,"Bonnell, Miss Elizabeth",58.0000,Southampton,"Birkdale, England Cleveland, Ohio",C-103,NaN,8,female
29,30,1st,0,"Borebank, Mr John James",NaN,Southampton,"London / Winnipeg, MB",D-21/2,NaN,NaN,male
...,...,...,...,...,...,...,...,...,...,...,...
1283,1284,3rd,0,"Vestrom, Miss Hulda Amanda Adolfina",NaN,NaN,NaN,NaN,NaN,NaN,female
1284,1285,3rd,0,"Vonk, Mr Jenko",NaN,NaN,NaN,NaN,NaN,NaN,male
1285,1286,3rd,0,"Ware, Mr Frederick",NaN,NaN,NaN,NaN,NaN,NaN,male
1286,1287,3rd,0,"Warren, Mr Charles William",NaN,NaN,NaN,NaN,NaN,NaN,male
1287,1288,3rd,0,"Wazli, Mr Yousif",NaN,NaN,NaN,NaN,NaN,NaN,male
1288,1289,3rd,0,"Webber, Mr James",NaN,NaN,NaN,NaN,NaN,NaN,male
1289,1290,3rd,1,"Wennerstrom, Mr August Edvard",NaN,NaN,NaN,NaN,NaN,NaN,male
1290,1291,3rd,0,"Wenzel, Mr Linhart",NaN,NaN,NaN,NaN,NaN,NaN,male
1291,1292,3rd,0,"Widegren, Mr Charles Peter",NaN,NaN,NaN,NaN,NaN,NaN,male
1292,1293,3rd,0,"Wiklund, Mr Jacob Alfred",NaN,NaN,NaN,NaN,NaN,NaN,male
1293,1294,3rd,1,"Wilkes, Mrs Ellen",NaN,NaN,NaN,NaN,NaN,NaN,female
1294,1295,3rd,0,"Willer, Mr Aaron",NaN,NaN,NaN,NaN,NaN,NaN,male
1295,1296,3rd,0,"Willey, Mr Edward",NaN,NaN,NaN,NaN,NaN,NaN,male
1296,1297,3rd,0,"Williams, Mr Howard Hugh",NaN,NaN,NaN,NaN,NaN,NaN,male
1297,1298,3rd,0,"Williams, Mr Leslie",NaN,NaN,NaN,NaN,NaN,NaN,male
1298,1299,3rd,0,"Windelov, Mr Einar",NaN,NaN,NaN,NaN,NaN,NaN,male
1299,1300,3rd,0,"Wirz, Mr Albert",NaN,NaN,NaN,NaN,NaN,NaN,male
1300,1301,3rd,0,"Wiseman, Mr Phillippe",NaN,NaN,NaN,NaN,NaN,NaN,male
1301,1302,3rd,0,"Wittevrongel, Mr Camiel",NaN,NaN,NaN,NaN,NaN,NaN,male
1302,1303,3rd,1,"Yalsevac, Mr Ivan",NaN,NaN,NaN,NaN,NaN,NaN,male
1303,1304,3rd,0,"Yasbeck, Mr Antoni",NaN,NaN,NaN,NaN,NaN,NaN,male
1304,1305,3rd,1,"Yasbeck, Mrs Antoni",NaN,NaN,NaN,NaN,NaN,NaN,female
1305,1306,3rd,0,"Youssef, Mr Gerios",NaN,NaN,NaN,NaN,NaN,NaN,male
1306,1307,3rd,0,"Zabour, Miss Hileni",NaN,NaN,NaN,NaN,NaN,NaN,female
1307,1308,3rd,0,"Zabour, Miss Tamini",NaN,NaN,NaN,NaN,NaN,NaN,female
1308,1309,3rd,0,"Zakarian, Mr Artun",NaN,NaN,NaN,NaN,NaN,NaN,male
1309,1310,3rd,0,"Zakarian, Mr Maprieder",NaN,NaN,NaN,NaN,NaN,NaN,male
1310,1311,3rd,0,"Zenn, Mr Philip",NaN,NaN,NaN,NaN,NaN,NaN,male
1311,1312,3rd,0,"Zievens, Rene",NaN,NaN,NaN,NaN,NaN,NaN,female
1312,1313,3rd,0,"Zimmerman, Leo",NaN,NaN,NaN,NaN,NaN,NaN,male

In [5]:
# 选取有用的特征值和目标值(字段)
titanic = data[["pclass", "survived", "age", "sex"]]

In [6]:
titanic

     pclass  survived      age     sex
0       1st         1  29.0000  female
1       1st         0   2.0000  female
2       1st         0  30.0000    male
3       1st         0  25.0000  female
4       1st         1   0.9167    male
5       1st         1  47.0000    male
6       1st         1  63.0000  female
7       1st         0  39.0000    male
8       1st         1  58.0000  female
9       1st         0  71.0000    male
10      1st         0  47.0000    male
11      1st         1  19.0000  female
12      1st         1      NaN  female
13      1st         1      NaN    male
14      1st         0      NaN    male
15      1st         1  50.0000  female
16      1st         0  24.0000    male
17      1st         0  36.0000    male
18      1st         1  37.0000    male
19      1st         1  47.0000  female
20      1st         1  26.0000    male
21      1st         0  25.0000    male
22      1st         1  25.0000    male
23      1st         1  19.0000  female
24      1st         1  28.0000    male
25      1st         0  45.0000    male
26      1st         1  39.0000    male
27      1st         1  30.0000  female
28      1st         1  58.0000  female
29      1st         0      NaN    male
...     ...       ...      ...     ...
1283    3rd         0      NaN  female
1284    3rd         0      NaN    male
1285    3rd         0      NaN    male
1286    3rd         0      NaN    male
1287    3rd         0      NaN    male
1288    3rd         0      NaN    male
1289    3rd         1      NaN    male
1290    3rd         0      NaN    male
1291    3rd         0      NaN    male
1292    3rd         0      NaN    male
1293    3rd         1      NaN  female
1294    3rd         0      NaN    male
1295    3rd         0      NaN    male
1296    3rd         0      NaN    male
1297    3rd         0      NaN    male
1298    3rd         0      NaN    male
1299    3rd         0      NaN    male
1300    3rd         0      NaN    male
1301    3rd         0      NaN    male
1302    3rd         1      NaN    male
1303    3rd         0      NaN    male
1304    3rd         1      NaN  female
1305    3rd         0      NaN    male
1306    3rd         0      NaN  female
1307    3rd         0      NaN  female
1308    3rd         0      NaN    male
1309    3rd         0      NaN    male
1310    3rd         0      NaN    male
1311    3rd         0      NaN  female
1312    3rd         0      NaN    male

[1313 rows x 4 columns]

In [9]:
# 查看缺失值,这个方法有可能不会显示有缺失值
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 4 columns):
pclass      1313 non-null object
survived    1313 non-null int64
age         633 non-null float64
sex         1313 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 41.1+ KB

In [10]:
titanic.isnull().any()

pclass      False
survived    False
age          True
sex         False
dtype: bool

In [12]:
# 填补age的缺失值,按照age的平均值填补,inplace重写
titanic["age"].fillna(titanic["age"].mean(), inplace=True)

C:\Users\chain\Anaconda3\lib\site-packages\pandas\core\generic.py:5434: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [13]:
# 再次检测是否还有缺失值
titanic.isnull().any()

pclass      False
survived    False
age         False
sex         False
dtype: bool

In [17]:
# 筛选特征值和目标值
x = titanic[["pclass", "age", "sex"]]  # pclass:仓位 age:年龄 sex:性别
y = titanic["survived"]  # survived:幸存者

In [18]:
x

     pclass        age     sex
0       1st  29.000000  female
1       1st   2.000000  female
2       1st  30.000000    male
3       1st  25.000000  female
4       1st   0.916700    male
5       1st  47.000000    male
6       1st  63.000000  female
7       1st  39.000000    male
8       1st  58.000000  female
9       1st  71.000000    male
10      1st  47.000000    male
11      1st  19.000000  female
12      1st  31.194181  female
13      1st  31.194181    male
14      1st  31.194181    male
15      1st  50.000000  female
16      1st  24.000000    male
17      1st  36.000000    male
18      1st  37.000000    male
19      1st  47.000000  female
20      1st  26.000000    male
21      1st  25.000000    male
22      1st  25.000000    male
23      1st  19.000000  female
24      1st  28.000000    male
25      1st  45.000000    male
26      1st  39.000000    male
27      1st  30.000000  female
28      1st  58.000000  female
29      1st  31.194181    male
...     ...        ...     ...
1283    3rd  31.194181  female
1284    3rd  31.194181    male
1285    3rd  31.194181    male
1286    3rd  31.194181    male
1287    3rd  31.194181    male
1288    3rd  31.194181    male
1289    3rd  31.194181    male
1290    3rd  31.194181    male
1291    3rd  31.194181    male
1292    3rd  31.194181    male
1293    3rd  31.194181  female
1294    3rd  31.194181    male
1295    3rd  31.194181    male
1296    3rd  31.194181    male
1297    3rd  31.194181    male
1298    3rd  31.194181    male
1299    3rd  31.194181    male
1300    3rd  31.194181    male
1301    3rd  31.194181    male
1302    3rd  31.194181    male
1303    3rd  31.194181    male
1304    3rd  31.194181  female
1305    3rd  31.194181    male
1306    3rd  31.194181  female
1307    3rd  31.194181  female
1308    3rd  31.194181    male
1309    3rd  31.194181    male
1310    3rd  31.194181    male
1311    3rd  31.194181  female
1312    3rd  31.194181    male

[1313 rows x 3 columns]

In [19]:
y

0       1
1       0
2       0
3       0
4       1
5       1
6       1
7       0
8       1
9       0
10      0
11      1
12      1
13      1
14      0
15      1
16      0
17      0
18      1
19      1
20      1
21      0
22      1
23      1
24      1
25      0
26      1
27      1
28      1
29      0
       ..
1283    0
1284    0
1285    0
1286    0
1287    0
1288    0
1289    1
1290    0
1291    0
1292    0
1293    1
1294    0
1295    0
1296    0
1297    0
1298    0
1299    0
1300    0
1301    0
1302    1
1303    0
1304    1
1305    0
1306    0
1307    0
1308    0
1309    0
1310    0
1311    0
1312    0
Name: survived, Length: 1313, dtype: int64

In [20]:
# 转换成字典
x = x.to_dict(orient="records")

In [21]:
x

[{'pclass': '1st', 'age': 29.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 2.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 30.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 25.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 0.9167, 'sex': 'male'},
 {'pclass': '1st', 'age': 47.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 63.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 39.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 58.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 71.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 47.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 19.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 50.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 24.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 37.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 47.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 26.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 25.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 25.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 19.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 28.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 45.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 39.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 30.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 58.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 45.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 22.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 41.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 48.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 44.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 59.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 60.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 45.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 53.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 58.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 33.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 14.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 11.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 49.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 46.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 47.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 27.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 27.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 26.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 64.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 37.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 39.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 55.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 70.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 69.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 39.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 38.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 27.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 27.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 17.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 4.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 27.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 50.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 48.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 49.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 48.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 39.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 23.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 53.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 30.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 24.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 19.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 28.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 23.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 64.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 60.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 49.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 44.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 22.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 60.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 48.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 37.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 35.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 47.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 22.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 45.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 49.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 71.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 54.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 38.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 19.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 58.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 45.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 23.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 46.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 25.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 21.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 48.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 49.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 45.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 55.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 52.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 24.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 16.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 44.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 51.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 42.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 35.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 35.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 38.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 35.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 50.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 49.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 46.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 58.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 41.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 42.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 40.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 42.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 55.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 50.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 16.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 29.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 21.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 30.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 15.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 30.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 46.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 54.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 28.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 65.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 33.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 44.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 37.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 55.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 47.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 58.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 23.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 19.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 64.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 64.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 22.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 28.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 22.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 18.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 17.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 52.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 46.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 56.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 43.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 33.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 27.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 55.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 54.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 61.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 48.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 18.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 13.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 21.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 34.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 40.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 50.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 39.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 56.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 28.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 56.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 56.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 24.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 18.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 24.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 23.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 45.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 40.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 6.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 57.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 32.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 62.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 54.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 43.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 52.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 62.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 67.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 63.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 61.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 46.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 52.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 39.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 18.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 48.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 49.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 39.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 17.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 46.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 61.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 47.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 64.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 60.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 60.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 55.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 54.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 21.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 57.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 45.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 50.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 50.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 27.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 20.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 51.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 21.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 36.0, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 40.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 32.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 33.0, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '1st', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '2nd', 'age': 30.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 28.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 18.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '2nd', 'age': 34.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 32.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 57.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 18.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 23.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 36.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 28.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 51.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 32.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 19.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 28.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 36.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 4.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 1.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 12.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 34.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 19.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 23.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 26.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '2nd', 'age': 27.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 15.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 45.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 40.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 20.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 25.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 36.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 25.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '2nd', 'age': 42.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 26.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 26.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 0.8333, 'sex': 'male'},
 {'pclass': '2nd', 'age': 31.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 31.19418104265403, 'sex': 'male'},
 {'pclass': '2nd', 'age': 19.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 54.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 44.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 52.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 30.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 30.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '2nd', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '2nd', 'age': 29.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '2nd', 'age': 29.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 27.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 24.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 35.0, 'sex': 'male'},
 {'pclass': '2nd', 'age': 31.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 8.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 22.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 30.0, 'sex': 'female'},
 {'pclass': '2nd', 'age': 31.19418104265403, 'sex': 'female'},
 {'pclass': '2nd', 'age': 20.0, 'sex': 'male'},

In [24]:
# 划分训练和测试数据集
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [25]:
# 字典特征抽取
from sklearn.feature_extraction import DictVectorizer
transfer = DictVectorizer()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)
x_train.toarray()

array([[31.19418104,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ],
       [65.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ],
       [31.19418104,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ],
       ...,
       [31.19418104,  0.        ,  0.        ,  1.        ,  1.        ,
         0.        ],
       [46.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ],
       [31.19418104,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ]])

In [27]:
# 所有不同的可能性
transfer.get_feature_names()

['age', 'pclass=1st', 'pclass=2nd', 'pclass=3rd', 'sex=female', 'sex=male']

## 决策树

In [28]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
# 4、决策树预估器流程
# 1）实例化预估器类
estimator = DecisionTreeClassifier(criterion="entropy")

# 2）调用fit进行训练
estimator.fit(x_train, y_train)

# 3）得出预测结果
y_predict = estimator.predict(x_test)
print("预测结果：\n", y_predict)

# 4）模型评估
# 1）对比真实值和预测值
print("对比真实值和预测值:\n", y_predict == y_test)
# 2）直接计算准确率
accuracy = estimator.score(x_test, y_test)
print("准确率为：\n", accuracy)

# 保存树到本地
export_graphviz(estimator, out_file="titanic67.dot", feature_names=transfer.get_feature_names())

预测结果：
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0
 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0
 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 0 0 0 1 0 1 1]
对比真实值和预测值:
 658     False
7        True
206      True
279      True
475      True
138      True
677      True
537     False
982     False
421      True
1156     True
438      True
696      True
284      True
1043     True
1216     True
905      True
8        True
842      True
654      True
1133     True
227      True
117      True
120     False
795      True
140      True
667      True
398      True
270      True
203     False
        ...
925      True
854      True
69       True
1052     True
760      True
727      True
357      True
1280     True
816      True
724      True
678      True
976     False
710      True
898      True
491      True
928      True
177     False
310      True
1211     True
181     False
182      True
301      True
257      True
1207    False
1130     True
872      True
473     False
60      False
242      True
162      True
Name: survived, Length: 329, dtype: bool
准确率为：
 0.7750759878419453

#### 决策树API当中，如果没有指定max_depth那么会根据信息熵的条件直到最终结束。
#### 这里我们可以指定树的深度来进行限制树的大小

In [31]:
# 1）实例化预估器类
estimator = DecisionTreeClassifier(criterion="entropy", max_depth=5)

# 2）调用fit进行训练
estimator.fit(x_train, y_train)

# 3）得出预测结果
y_predict = estimator.predict(x_test)
print("预测结果：\n", y_predict)

# 4）模型评估
# 1）对比真实值和预测值
print("对比真实值和预测值:\n", y_predict == y_test)
# 2）直接计算准确率
accuracy = estimator.score(x_test, y_test)
print("准确率为：\n", accuracy)

# 保存树到本地
export_graphviz(estimator, out_file="titanic67.dot", feature_names=transfer.get_feature_names())

预测结果：
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0
 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0
 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 1 0 1 1]
对比真实值和预测值:
 658     False
7        True
206      True
279      True
475      True
138      True
677      True
537     False
982     False
421      True
1156     True
438      True
696      True
284      True
1043     True
1216     True
905      True
8        True
842      True
654      True
1133     True
227      True
117     False
120     False
795      True
140      True
667      True
398      True
270      True
203     False
        ...
925      True
854      True
69       True
1052     True
760      True
727      True
357      True
1280     True
816      True
724      True
678      True
976     False
710      True
898      True
491      True
928      True
177      True
310      True
1211     True
181      True
182      True
301      True
257      True
1207    False
1130     True
872      True
473     False
60      False
242      True
162      True
Name: survived, Length: 329, dtype: bool
准确率为：
 0.790273556231003

## 随机森林

In [38]:
from sklearn.ensemble import RandomForestClassifier
# 随机森林预估器
estimator = RandomForestClassifier()
# 准备调参字典,定义超参数的选择列表
param_dict = {"n_estimators": [120,200,300,500,800,1200], "max_depth": [5,8,15,25,30]}

In [39]:
from sklearn.model_selection import GridSearchCV
estimator = GridSearchCV(estimator, param_grid=param_dict, cv=3)
# 2）调用fit进行训练
estimator.fit(x_train, y_train)

# 3）得出预测结果
y_predict = estimator.predict(x_test)
print("预测结果：\n", y_predict)

# 4）模型评估
# 1）对比真实值和预测值
print("对比真实值和预测值:\n", y_predict == y_test)
# 2）直接计算准确率
accuracy = estimator.score(x_test, y_test)
print("准确率为：\n", accuracy)

# 查看调优结果
print("最佳参数:\n", estimator.best_params_)
print("最佳结果:\n", estimator.best_score_)
print("最佳估计器:\n", estimator.best_estimator_)
print("交叉验证结果:\n", estimator.cv_results_)

预测结果：
 [0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0
 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0
 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0
 0 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 1 0 1 1]
对比真实值和预测值:
 658     False
7        True
206      True
279      True
475      True
138      True
677      True
537      True
982     False
421      True
1156     True
438      True
696      True
284      True
1043     True
1216     True
905      True
8        True
842      True
654      True
1133     True
227      True
117     False
120     False
795      True
140      True
667      True
398      True
270      True
203     False
        ...
925      True
854      True
69       True
1052     True
760      True
727      True
357      True
1280     True
816      True
724      True
678      True
976     False
710      True
898      True
491      True
928      True
177      True
310      True
1211     True
181      True
182      True
301      True
257      True
1207    False
1130     True
872      True
473     False
60      False
242      True
162      True
Name: survived, Length: 329, dtype: bool
准确率为：
 0.7933130699088146
最佳参数:
 {'max_depth': 5, 'n_estimators': 300}
最佳结果:
 0.8363821138211383
最佳估计器:
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
交叉验证结果:
 {'mean_fit_time': array([0.10771227, 0.1737802 , 0.268478  , 0.44447533, 0.69235563,
       1.03963025, 0.12018069, 0.19921192, 0.29956039, 0.49862067,
       0.80429935, 1.20573854, 0.12682827, 0.21712732, 0.34416326,
       0.54022098, 0.90331006, 1.32579231, 0.12851914, 0.21808434,
       0.32764292, 0.54304552, 0.86274831, 1.29806765, 0.12867657,
       0.20981741, 0.32000311, 0.53468887, 0.860442  , 1.27354685]), 'std_fit_time': array([0.00354917, 0.00128595, 0.00873614, 0.01109919, 0.00295425,
       0.0073098 , 0.00040755, 0.00209438, 0.00332572, 0.00336256,
       0.00875918, 0.01942627, 0.0019267 , 0.00511757, 0.0105949 ,
       0.00936751, 0.05242357, 0.00539491, 0.00188178, 0.00694894,
       0.01106341, 0.00643904, 0.00995865, 0.03541995, 0.0021463 ,
       0.00167259, 0.00749462, 0.01071993, 0.01320035, 0.02049632]), 'mean_score_time': array([0.00764577, 0.01227681, 0.01893775, 0.03026358, 0.04751372,
       0.07216485, 0.00799131, 0.01297808, 0.01946306, 0.0325671 ,
       0.05084419, 0.07848819, 0.00833718, 0.01331051, 0.02095421,
       0.03358897, 0.05560764, 0.07911269, 0.00829991, 0.01428278,
       0.02197544, 0.03559335, 0.05385685, 0.08075897, 0.00865658,
       0.01330924, 0.02891978, 0.03392442, 0.05219348, 0.08015744]), 'std_score_time': array([4.69797234e-04, 4.63224264e-04, 1.64656565e-05, 4.62189460e-04,
       9.28864240e-04, 4.77818605e-04, 3.35896721e-05, 1.73713201e-05,
       4.23246949e-04, 4.35854653e-04, 1.39890294e-05, 1.87795345e-03,
       4.76344742e-04, 4.63099899e-04, 1.40331972e-03, 4.78869729e-04,
       3.35475547e-03, 4.77655675e-04, 4.78928681e-04, 4.79478251e-04,
       2.77757360e-05, 4.84468052e-04, 1.40989641e-03, 3.23957367e-03,
       4.72953291e-04, 4.61639489e-04, 9.24454611e-03, 8.04434446e-04,
       4.44164378e-04, 1.63179735e-03]), 'param_max_depth': masked_array(data=[5, 5, 5, 5, 5, 5, 8, 8, 8, 8, 8, 8, 15, 15, 15, 15, 15,
                   15, 25, 25, 25, 25, 25, 25, 30, 30, 30, 30, 30, 30],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_n_estimators': masked_array(data=[120, 200, 300, 500, 800, 1200, 120, 200, 300, 500, 800,
                   1200, 120, 200, 300, 500, 800, 1200, 120, 200, 300,
                   500, 800, 1200, 120, 200, 300, 500, 800, 1200],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'max_depth': 5, 'n_estimators': 120}, {'max_depth': 5, 'n_estimators': 200}, {'max_depth': 5, 'n_estimators': 300}, {'max_depth': 5, 'n_estimators': 500}, {'max_depth': 5, 'n_estimators': 800}, {'max_depth': 5, 'n_estimators': 1200}, {'max_depth': 8, 'n_estimators': 120}, {'max_depth': 8, 'n_estimators': 200}, {'max_depth': 8, 'n_estimators': 300}, {'max_depth': 8, 'n_estimators': 500}, {'max_depth': 8, 'n_estimators': 800}, {'max_depth': 8, 'n_estimators': 1200}, {'max_depth': 15, 'n_estimators': 120}, {'max_depth': 15, 'n_estimators': 200}, {'max_depth': 15, 'n_estimators': 300}, {'max_depth': 15, 'n_estimators': 500}, {'max_depth': 15, 'n_estimators': 800}, {'max_depth': 15, 'n_estimators': 1200}, {'max_depth': 25, 'n_estimators': 120}, {'max_depth': 25, 'n_estimators': 200}, {'max_depth': 25, 'n_estimators': 300}, {'max_depth': 25, 'n_estimators': 500}, {'max_depth': 25, 'n_estimators': 800}, {'max_depth': 25, 'n_estimators': 1200}, {'max_depth': 30, 'n_estimators': 120}, {'max_depth': 30, 'n_estimators': 200}, {'max_depth': 30, 'n_estimators': 300}, {'max_depth': 30, 'n_estimators': 500}, {'max_depth': 30, 'n_estimators': 800}, {'max_depth': 30, 'n_estimators': 1200}], 'split0_test_score': array([0.8445122 , 0.8445122 , 0.84756098, 0.84146341, 0.8445122 ,
       0.8445122 , 0.82621951, 0.82012195, 0.82926829, 0.82621951,
       0.82926829, 0.82621951, 0.81707317, 0.82012195, 0.81402439,
       0.81402439, 0.82012195, 0.82012195, 0.81707317, 0.80792683,
       0.82012195, 0.81402439, 0.81097561, 0.82012195, 0.80487805,
       0.82012195, 0.82012195, 0.81402439, 0.82012195, 0.81097561]), 'split1_test_score': array([0.82317073, 0.82317073, 0.82317073, 0.82317073, 0.82317073,
       0.82317073, 0.81707317, 0.81707317, 0.82317073, 0.81707317,
       0.82012195, 0.82012195, 0.81402439, 0.81707317, 0.81402439,
       0.81402439, 0.81707317, 0.81707317, 0.81707317, 0.81707317,
       0.81707317, 0.81707317, 0.81402439, 0.81707317, 0.81402439,
       0.81402439, 0.81402439, 0.81402439, 0.81707317, 0.81707317]), 'split2_test_score': array([0.83231707, 0.83841463, 0.83841463, 0.83841463, 0.83536585,
       0.83841463, 0.82621951, 0.82621951, 0.82621951, 0.82621951,
       0.82621951, 0.82621951, 0.80792683, 0.81097561, 0.81402439,
       0.81402439, 0.81097561, 0.81402439, 0.81097561, 0.80792683,
       0.81402439, 0.81402439, 0.81402439, 0.81402439, 0.81707317,
       0.81707317, 0.81707317, 0.81097561, 0.81402439, 0.81402439]), 'mean_test_score': array([0.83333333, 0.83536585, 0.83638211, 0.83434959, 0.83434959,
       0.83536585, 0.82317073, 0.82113821, 0.82621951, 0.82317073,
       0.82520325, 0.82418699, 0.81300813, 0.81605691, 0.81402439,
       0.81402439, 0.81605691, 0.81707317, 0.81504065, 0.81097561,
       0.81707317, 0.81504065, 0.81300813, 0.81707317, 0.81199187,
       0.81707317, 0.81707317, 0.81300813, 0.81707317, 0.81402439]), 'std_test_score': array([0.0087422 , 0.00897537, 0.01006046, 0.00800204, 0.0087422 ,
       0.00897537, 0.00431163, 0.0038025 , 0.00248932, 0.00431163,
       0.0038025 , 0.00287442, 0.0038025 , 0.0038025 , 0.        ,
       0.        , 0.0038025 , 0.00248932, 0.00287442, 0.00431163,
       0.00248932, 0.00143721, 0.00143721, 0.00248932, 0.00518193,
       0.00248932, 0.00248932, 0.00143721, 0.00248932, 0.00248932]), 'rank_test_score': array([ 6,  2,  1,  4,  4,  2, 10, 12,  7, 10,  8,  9, 26, 19, 23, 23, 19,
       13, 21, 30, 13, 21, 26, 13, 29, 13, 13, 26, 13, 23]), 'split0_train_score': array([0.85213415, 0.85060976, 0.85365854, 0.85365854, 0.85365854,
       0.85213415, 0.86432927, 0.86585366, 0.86585366, 0.86737805,
       0.86585366, 0.86585366, 0.87195122, 0.87195122, 0.87195122,
       0.87195122, 0.87195122, 0.87195122, 0.87195122, 0.87195122,
       0.87195122, 0.87195122, 0.87195122, 0.87195122, 0.87195122,
       0.87195122, 0.87195122, 0.87195122, 0.87195122, 0.87195122]), 'split1_train_score': array([0.8597561 , 0.86280488, 0.86280488, 0.86280488, 0.86280488,
       0.86280488, 0.88109756, 0.88109756, 0.87804878, 0.87957317,
       0.87957317, 0.87957317, 0.88109756, 0.88109756, 0.88109756,
       0.88109756, 0.88109756, 0.88109756, 0.88109756, 0.88109756,
       0.88109756, 0.88109756, 0.88109756, 0.88109756, 0.88109756,
       0.88109756, 0.88109756, 0.88109756, 0.88109756, 0.88109756]), 'split2_train_score': array([0.85518293, 0.85670732, 0.85670732, 0.85518293, 0.85670732,
       0.85518293, 0.87042683, 0.87195122, 0.87042683, 0.87195122,
       0.87195122, 0.87195122, 0.875     , 0.875     , 0.875     ,
       0.875     , 0.875     , 0.875     , 0.875     , 0.875     ,
       0.875     , 0.875     , 0.875     , 0.875     , 0.875     ,
       0.875     , 0.875     , 0.875     , 0.875     , 0.875     ]), 'mean_train_score': array([0.85569106, 0.85670732, 0.85772358, 0.85721545, 0.85772358,
       0.85670732, 0.87195122, 0.87296748, 0.87144309, 0.87296748,
       0.87245935, 0.87245935, 0.87601626, 0.87601626, 0.87601626,
       0.87601626, 0.87601626, 0.87601626, 0.87601626, 0.87601626,
       0.87601626, 0.87601626, 0.87601626, 0.87601626, 0.87601626,
       0.87601626, 0.87601626, 0.87601626, 0.87601626, 0.87601626]), 'std_train_score': array([0.00313232, 0.00497864, 0.0038025 , 0.00400102, 0.0038025 ,
       0.00448768, 0.00692997, 0.00626465, 0.00503023, 0.00503023,
       0.00561248, 0.00561248, 0.0038025 , 0.0038025 , 0.0038025 ,
       0.0038025 , 0.0038025 , 0.0038025 , 0.0038025 , 0.0038025 ,
       0.0038025 , 0.0038025 , 0.0038025 , 0.0038025 , 0.0038025 ,
       0.0038025 , 0.0038025 , 0.0038025 , 0.0038025 , 0.0038025 ])}